### ISSUE TITLE
Allways true condition

### ISSUE THREAD

**Issue by werogg** [koczadly/csgo-gsi#2]
Just checked that my IDE is warning about this allways 'true' condition. Could be fast fixed.

https://github.com/koczadly/csgo-gsi/blob/ab263f20b49fba71fdb5e3f96a5d7594f63cd62e/src/main/java/uk/oczadly/karl/csgsi/state/PlayerState.java#L162

**Comment by koczadly** [comment]
Ah thanks for spotting that, seems like I was accessing the variable before the null check. Fixed that up a little - not sure if the null check is absolutely necessary, but I've left it there in case it breaks something.
