### ISSUE TITLE
Missing weapons on PlayerState#Weapon

### ISSUE THREAD

**Issue by werogg** [koczadly/csgo-gsi#3]
These weapons are missing on the PlayerState#Weapon enum. I don't know if there's any other weapon missing, these are all the listed ones on Valve's CS:GO documentation.

* weapon_bumpmine
* weapon_diversion
* weapon_mp5sd
* weapon_hammer
* weapon_shield
* weapon_snowball
* weapon_spanner
* weapon_tablet
* weapon_knife_ghost
* weapon_fists
* weapon_zone_repulsor

**Comment by koczadly** [comment]
Hopefully they're all added now.

**Comment by koczadly** [comment]
Added special class [DeserializedEnum](https://github.com/koczadly/csgo-gsi/blob/fa300a0c83fd4b0c54f299d2747a98a24562400f/src/main/java/uk/oczadly/karl/csgsi/state/components/DeserializedEnum.java) for enums, allowing you to retrieve the original string value even if it's not specified within the enum. Will break some compatibility with projects using the older API, but I'm sure there's not many using the library tbh. Let me know if you run into any issues!
