### ISSUE TITLE
How to get whether a CT has a defusing kit?

### ISSUE THREAD

**Issue by IntelliCe** [koczadly/csgo-gsi#4]
It seems not in the weapon inventory, but I haven't found the related method to get it. I also have searched in the whole project using keyword KIT but it returned nothing.

**Comment by koczadly** [comment]
Sorry, I appear to have either missed this, or it's only recently been added. Will push a new version in a few hours, and can be retrieved like so:

`PlayerState.getState().hasDefuseKit()`

**Comment by koczadly** [comment]
Hey, version `1.4.0` has finally been deployed to Maven central (might take some time for it to become available).

Apologies in advance, but I had to change a few class and method names for clarity — should be a quick fix, but you'll need to update any usages in your code. The inventory system was also slightly revamped, which isn't compatible with the previous API (although it should also be a quick fix).

**Comment by koczadly** [comment]
**Update:** Please use version `1.4.1` instead, `1.4.0`, the latter has a bug which throttles the updates to only once per second which may be too slow for your project.

**Comment by IntelliCe** [comment]
Got it. Thanks for your maintenance.

**Comment by koczadly** [comment]
Sorry, please update to `1.4.2`. There's a bug which causes the wrong state to appear in the previous context, which will break your application.
