### ISSUE TITLE
Serverside implementation of GSI

### ISSUE THREAD

**Issue by ogmii** [koczadly/csgo-gsi#8]
Hello koczadly,

first of all, sorry for posting this as issue since it is not really an issue, I didn't find any other way to contact you.

I used your library with my local installation of CSGO and was able to get it working without any problems (= I received states from the game) 👍 

For my current project I need to implement this solution on the serverside. I've ordered CSGO server, tried to add gamestate_integration cfg file, but didn't receive any states. So my question is: Is it even possible to implement your solution on the serverside? I've already seen clues that it probably won't work but I'm looking for confirmation.

Alternatively, are there any other solutions to get game states from server? Would you recommend some? The goal is to have live statistics from the game presented on a website.

Once again, sorry for posting this as an issue, looking forward for your answers.

Martin.

**Comment by koczadly** [comment]
Heya, no worries at all mate. I'll have to keep this short cos I'm on my phone at the minute. From my understanding, there's no game state integration from the server side, and it's only offered by the game client.

get5, a popular CSGO sourcemod plugin does seem to offer event notifications, but not actual state information (if your usage requires that). You could use that, though this library doesn't support that format and setup. More info here: https://github.com/splewis/get5/wiki/Event-logs

**Comment by ogmii** [comment]
@koczadly thanks a lot for your reply ❤️ In the end I managed to enable sending CS logs to specified URL where I can parse them and forward them for further processing.

**Comment by ogmii** [comment]
@koczadly thanks a lot for your reply ❤️ In the end I managed to enable sending CS logs to specified URL where I can parse them and forward them for further processing.
